### ISSUE TITLE
Implications of a shared runtime library

### ISSUE THREAD

**Issue by SamuraiCrow** [turbolent/w2c2#39]
On Haiku, open source runtimes are preferred to be shared to save on memory (reentrant position-independent code) and to improve debugging maintainability at the package manager also.  I've already added a boolean option to the CMakefiles.txt on my fork for a shared runtime easily.  Apart from needing to change the name to something like libw2c2runtime.dll/so/dylib/whatever to avoid a name collision with WABT's implementation, are there any negative impacts to consider when using shared libraries on other platforms?

**Comment by turbolent** [comment]
Do you mean the "runtime" portion for w2c2 needed for a WebAssembly binary, i.e. https://github.com/turbolent/w2c2/blob/main/w2c2_base.h, or do you mean the WASI library?

For the former, it is so little/so small that I don't think it makes much sense to build shared library. For the latter, this should be pretty easy to support, I recently separated the build system of the wasi library from the w2c2 program (see the separate Makefile /CMake config). For now I'm statically linking it into the example programs, because it's easier to distribute the resulting binary, but I don't think there should be any problems in packaging and distributing the wasi library as a separate shard library.

**Comment by SamuraiCrow** [comment]
Thanks!  I was referring to wasi.a becoming shared.  On 64-bit Haiku, the shared object generated was about half the size of the linker archive besides the other two reasons I gave in my original post.  The main reason I brought up the issue was the name collision with WABT's WASI implementation also being called libwasi.so when compiled as a shared library.

I'd be surprised if that header generated any sharable code considering all the inlines and preprocessor macros!  But no.  I wasn't referring to that one.

**Comment by turbolent** [comment]
With "WABT's WASI implementation", do you mean the one for the interpreter, i.e. https://github.com/WebAssembly/wabt/blob/main/src/interp/interp-wasi.cc?

**Comment by SamuraiCrow** [comment]
I think so.  Is it the one that Wasm2C uses?  They should be API if not ABI compatible though, now that I think about it.

**Comment by SamuraiCrow** [comment]
I'll assume that the shared libraries are compatible enough and close this.

**Comment by turbolent** [comment]
w2c2 and wasm2c generate different code, imports/exports are not compatible between both. In case you want to have both available on a single system, I recommend solving potential naming clashes when packaging, e.g. renaming w2c2's wasi library to something else - it is not required to have a particular name

**Comment by SamuraiCrow** [comment]
Ok.  I'll see if I can get a simple pull request ready.
