### ISSUE TITLE
the remaining WASI function calls

### ISSUE THREAD

**Issue by SamuraiCrow** [turbolent/w2c2#53]
I'm willing to help implement the remaining WASI function calls if you need me to.  I see that one of the incomplete ones is sched/yield which yields the current time slice in a multitasking OS.  It seems WASI preview 2 specification is coming up soon also.  Would you like to coordinate or would just submitting pull requests suffice?

**Comment by turbolent** [comment]
Hi Samuel! 

Thank you for offering to contribute implementations! The missing WASI function calls are mainly just not implemented yet because I hadn't come across them in any binaries or they were not critical in the binaries I tried (e.g. clang and Python). 

There are also a couple function calls which are provided, but are just stubs and are actually not implemented yet, i.e. [`fd_fdstat_set_flags`](https://github.com/turbolent/w2c2/blob/3570229ced5dc2dd7c71bcd607a51964eb315393/wasi/wasi.c#L3631) and 
[`poll_oneoff`](https://github.com/turbolent/w2c2/blob/3570229ced5dc2dd7c71bcd607a51964eb315393/wasi/wasi.c#L3644)

PRs are very welcome! Even though the chances are low, maybe open an issue for the function(s) you plan to implement when you start, to avoid potential duplicate work / coordinating. Thanks!

**Comment by SamuraiCrow** [comment]
Thanks!  I'll help out where I can!

**Comment by SamuraiCrow** [comment]
I thought I'd better note that WASI preview states are still in flux and diverging from POSIX standards in some cases.  Since some of the function definitions are changing or being eliminated, I've put this on hold.
